//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookstore.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Source = BookstoreDB1.mssql.somee.com; Integrated Security = False; User ID = PashaMayba_SQLLogin_1; Password = lbfic9ljyq; Connect Timeout = 30; Encrypt = False; TrustServerCertificate = False; ApplicationIntent = ReadWrite; MultiSubnetFailover = False;.
        /// </summary>
        public static string DataBaseLine {
            get {
                return ResourceManager.GetString("DataBaseLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Source =DESKTOP-2SQGFV4\SQLEXPRESS; Initial Catalog = BookstoreDB1.1; Integrated Security = True; Connect Timeout = 30; Encrypt = False; TrustServerCertificate = False; ApplicationIntent = ReadWrite; MultiSubnetFailover = False;.
        /// </summary>
        public static string Databaseline1 {
            get {
                return ResourceManager.GetString("Databaseline1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://www.liqpay.ua/api/3/checkout.
        /// </summary>
        public static string LiqyPatCheckoutURl {
            get {
                return ResourceManager.GetString("LiqyPatCheckoutURl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sandbox_3Sb02IvkSvwCuKPHtTdSxcVs1Om2m6mKLORAm2SJ.
        /// </summary>
        public static string LiqypayPrivateKey {
            get {
                return ResourceManager.GetString("LiqypayPrivateKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://www.liqpay.ua/api/request.
        /// </summary>
        public static string LiqyPayRequestURL {
            get {
                return ResourceManager.GetString("LiqyPayRequestURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sandbox_i44975687731.
        /// </summary>
        public static string LiqyPublicKey {
            get {
                return ResourceManager.GetString("LiqyPublicKey", resourceCulture);
            }
        }
    }
}
